imwheel/.imwheelrc    ${HOME}    linux
feh/.fehbg    ${HOME}    linux
i3/i3    ${HOME}/.config/i3    linux
i3/i3status    ${HOME}/.config/i3status    linux
fontconfig    ${HOME}/.config/fontconfig    linux
latex/.latexmkrc    ${HOME}
nvim    ${HOME}/.config/nvim
wezterm    ${HOME}/.config/wezterm
xorg/.Xmodmap    ${HOME}    linux
xorg/.xprofile    ${HOME}    linux
zsh/.zshrc    ${HOME}
zsh/zshrc.d    ${HOME}
